config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  resources :bands do
    resources :albums, on: :member, only: [:new]
  end

  resources :albums, except: [:new] do
    resources :tracks, on: :member, only: [:new]
  end

  resources :tracks, except: [:new] do
    resources :notes, on: :member, only: [:create]
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, presence: true
  validates :recording_type,
    inclusion: {in: %w(Live Studio)}
  validates :band_id, presence: true

  belongs_to(
    :band,
    class_name: 'Band',
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    dependent: :destroy,
    class_name: 'Track',
    foreign_key: :album_id,
    primary_key: :id
  )

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many(
    :albums,
    dependent: :destroy,
    class_name: 'Album',
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    through: :albums,
    source: :tracks
  )
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates_presence_of :user_id, :album_id, :body
  
  belongs_to :track
  belongs_to :author, class_name: 'User's
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :album_id, :track_type, presence: true
  validates :track_type, inclusion: {in: %w(regular bonus)}

  belongs_to(
    :album,
    class_name: 'Album',
    foreign_key: :album_id,
    primary_key: :id
  )

  has_one(
    :band,
    through: :album,
    source: :band
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  validates :email, presence: true
  validates :password, length: {minimum: 1, allow_nil: true}
  validates :password_digest, presence: {message: 'Must enter a password'}

  attr_reader :password

  def self.find_by_credentials(email, password)
    if email == '' or password == ''
      return nil
    end
    user = User.find_by(email: email)
    return nil if user.nil?
    password_digest = BCrypt::Password.new(user.password_digest)
    return user if password_digest.is_password?(password)
    nil
  end

  def User.generate_session_token
    session_token = SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    session_token = User.generate_session_token
    self.session_token = session_token
    self.save
    session_token
  end

  def ensure_session_token
    self.session_token ||= reset_session_token!
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_to_sign_in_page

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @bands = Band.all
    @band = Band.find(params[:band_id])
    @album = Album.new
    @album.band = @band
  end

  def create
    @bands = Band.all
    @band = Band.find(params[:album][:band_id])
    @album = Album.new(album_params)
    if @album.save!
      flash.now[:notice] = ['Successfully added album!']
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.new(album_params)
    if @album.save
      flash.now[:notice] = ['Successfully updated album info!']
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash.now[:notice] = ['Successfully removed album!']
    redirect_to albums_url
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :recording_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    session[:session_token] != nil
  end

  def sign_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def redirect_to_sign_in_page
    unless logged_in?
      flash[:notice] = ['You must be logged in to do that']
      redirect_to new_session_url
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :redirect_to_sign_in_page

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash.now[:notice] = ['Successfully added band!']
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      flash.now[:notice] = ['Successfully updated Band info!']
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    flash.now[:notice] = ['Successfully removed Band!']
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    byebug
    @note = Note.new(note_params)
    @user = current_user
    @track = Track.find(params[:id])
    @note.user = @user

    if @note.save

    else
      render
      flash.now[:errors] = @track.errors.full_messages
    end

  end

  private

  def note_params
    params.require(:note).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    flash.now[:errors] = nil
    @user = User.new
  end

  def create
    email = params[:user][:email]
    password = params[:user][:password]
    @user = User.find_by_credentials(email, password)
    if @user.nil?
      @user = User.new
      flash.now[:errors] = ["Incorrect email and password combination"]
      render :new
      return
    else
      session[:session_token] = @user.reset_session_token!
      flash.now[:notice] = 'Successfully signed in!'
      redirect_to user_url(@user)
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to users_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :redirect_to_sign_in_page

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
    @album = Album.find(params[:album_id])
    @band = @album.band
    @albums = @band.albums
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)

    @album = Album.find(params[:track][:album_id])

    @band = @album.band

    @albums = @band.albums

    if @track.save
      flash.now[:notice] = ['Successfully added track!']
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :track_type, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        sign_in(@user)
        redirect_to users_url
      else
        flash[:errors] = @user.errors.full_messages
        render :new
      end
    end

    def show
      @user = User.find(params[:id])
    end

    private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def insert_w_h1_heading(text)
    "<h1>#{text}</h1>".html_safe
  end


end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/albums/edit.html.erb
<h1> <%= @album.name %>
<h2>Edit album details</h2>

<form action='<%= album_url(@album) %>' method='POST'>
  <input type='hidden' name='_method' value='PATCH'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <label>
    Title
    <input type='text' name='album[title]' value='<%= @album.title %>'>
  </label>
  
  <label>
    Band
  </label>

  <label>
    Title
    <input type='text' name='album[title]' value='<%= @album.title %>'>
  </label>

  <input type='submit' value='Edit album'>
</form>

app/views/albums/index.html.erb
<h1>Albums</h1>

<% @albums.each do |album| %>
  <%= link_to "#{album.title}, #{album.band.name}", album_url(album) %>
<% end %>

app/views/albums/new.html.erb
<h1><%= @band.name %></h1>
<h2>Add Album</h2>

<%= render 'shared/flashes' %>

<form action='<%= albums_url %>' method='POST'>
  <input type='hidden' name='_method' value='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <label>
    Title
    <input type='text' name='album[title]' value='<%= @album.title %>'>
  </label>

  <label>
    Recording Type
    <label>
      Live
      <input type='radio' name='album[recording_type]' value='Live'>
    </label>
    <label>
      Studio
      <input type='radio' name='album[recording_type]' value='Studio'>
  </label>
  </label>

  <label>
    Band
    <select name='album[band_id]'>
      <% @bands.each do |band| %>
        <option value='<%= band.id %>'
          <% unless @album.band.nil? %>
            <%= "selected" if @album.band.id == band.id %>
          <% end %>
        >
          <%= band.name %>
        </option>
      <% end %>
    </select>
  </label>

  <input type='submit' value='Add album'>
</form>

app/views/albums/show.html.erb
<h1><%= @album.band.name %></h1>
<hr>


Album title:
<h2>
  <%= @album.title %>
</h2>

Recording type:
<%= @album.recording_type %>

<%= button_to "Back to band's page", band_url(@album.band), method: :get %>

<%= button_to "Add track", new_album_track_url(@album), method: :get %>

<br><BR>

<h3>Tracks</h3>
  <% @album.tracks.each do |track| %>
    <ul>
      <li>
        <%= link_to track.title, track_url(track) %>
      </li>
    </ul>
  <% end %>

<%= button_to 'Edit album', edit_album_url(@album), method: :get %>
<%= button_to 'Remove album', album_url(@album), method: :delete %>
<BR><BR>

app/views/bands/edit.html.erb
<h1> <%= @band.name %>
<h2>Edit band details</h2>

<form action='<%= band_url(@band) %>' method='POST'>
  <input type='hidden' name='_method' value='PATCH'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <label>
    Name
    <input type='text' name='band[name]' value='<%= @band.name %>'>
  </label>

  <input type='submit' value='Edit band'>
</form>

app/views/bands/index.html.erb
<h1>Bands Index</h1>
<% @bands.each do |band| %>
  <ul>
    <li>
      <%= link_to band.name, band_url(band) %>
    </li>
  </ul>
<% end %>

<%= button_to 'Add Band', new_band_url, method: :get %>

app/views/bands/new.html.erb
<h1>Add Band</h1>

<form action='<%= bands_url %>' method='POST'>
  <input type='hidden' name='_method' value='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
  <label>
    Name
    <input type='text' name='band[name]' value='<%= @band.name %>'>
  </label>

  <input type='submit' value='Add band'>
</form>

app/views/bands/show.html.erb
<%= insert_w_h1_heading("#{@band.name}'s Page") %>
<hr>
<%= button_to 'Back to all bands', bands_url, method: :get %>
<br><BR>
<h3>Albums</h3>
<% @band.albums.each do |album| %>
  <ul>
    <li>
      <%= link_to album.title, album_url(album) %>
    </li>
  </ul>
<% end %>

<%= button_to 'Add album', new_band_album_url(@band), method: :get %>
<%= button_to 'Edit Band', edit_band_url(@band), method: :get %>
<%= button_to 'Remove Band', band_url(@band), method: :delete %>
<BR><BR>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <strong><%= current_user.email %></strong>
  <%= button_to 'Sign Out', session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_flashes.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>
<BR><BR>
<% if flash[:notice] %>
  <% flash[:notice].each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_form.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <%= msg %>
    <br>
  <% end %>
  <br><BR>
<% end %>


<% if flash[:notice] %>
  <% flash[:notice].each do |msg| %>
    <%= msg %>
    <br>
  <% end %>
  <br><BR>
<% end %>

<form action='<%= action_url %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

  <label>
    Email
    <input type='text' name='user[email]' id='user_email'>
  </label>

  <label>
    Password
    <input type='password' name='user[password]' id='user_password'>
  </label>

  <input type='submit' value='<%= submit_button_text %>'>
</form>

<br><BR><BR>
<%= button_to "Reset #{reset_button_text} Page", reset_url, method: :get %>

app/views/tracks/_form.html.erb
<form action='<%= track_notes_url(track) %>' method='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

  <label>
    Note
    <BR>
      <textarea name='note[body]'></textarea>
  </label>

  <input type='submit' value='Submit Note'>
</form>

app/views/tracks/index.html.erb
Song Index

app/views/tracks/new.html.erb
<h1>Add Track</h1>

<%= render 'shared/flashes' %>

Band:
<%= link_to @band.name, band_url(@band) %>

<BR><BR>

Album:
<%= @album.title %>

<hr>

<form action='<%= tracks_url %>' method='POST'>
  <input type='hidden' name='_method' value='POST'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

  <label>
    Title
    <input type='text' name='track[title]' value='<%= @track.title %>'>
  </label>
  <BR><BR>

  <label>
    Album
    <select name='track[album_id]'>
      <% @albums.each do |album| %>
        <option value='<%= album.id %>'
          <%= "selected" if @track.album_id == album.id %>
        >
          <%= album.title %>
        </option>
      <% end %>
    </select>
  </label>
  <BR><BR>

  <label>
    Track Type
  </label>
  <p>
    <label>
      Bonus
      <input type='radio' name='track[track_type]' value='bonus'>
    </label>

    <label>
      Regular
      <input type='radio' name='track[track_type]' value='regular'>
    </label>
  </p>

  <input type='submit' value='Add track'>
</form>

app/views/tracks/show.html.erb
<%= @track.title %>
<HR>

Band
<%= @track.band.name %>

<BR><BR>

Album
<%= @track.album.title %>
<BR><BR>

<%= render 'tracks/form', track: @track %>

app/views/users/index.html.erb
All Our Users!!

<% @users.each do |user| %>
  <ul>
    <li>
      <%= user.email %>
    </li>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>
<br><BR>

<%= render 'shared/flashes' %>

<%= render 'shared/form', action_url: users_url, submit_button_text: 'Sign Up!', reset_button_text: 'Sign Up', reset_url: new_user_url %>

app/views/users/show.html.erb
<%= @user.email %>'s Page!!!!